name: 'Create GitHub Releases'
description: 'Create a GitHub release with automatic release notes'

runs:
  using: 'composite'
  runs-on: ubuntu-latest
  steps:
    - name: Create Release Notes
      uses: actions/github-script@v4.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.request(`POST /repos/${{ github.repository }}/releases`, {
            tag_name: '${{ github.ref }}',
            generate_release_notes: true
          });
