name: 'Increment Version'
description: 'Use the npm CLI to increment the version of a package.'
inputs:
  version-type:
    description: 'The type of version bump to be made'
    required: true
    default: 'patch'

runs:
  using: 'composite'
  runs-on: 'ubuntu-latest'
  steps:
  - name: 'Check out source'
    uses: actions/checkout@v2

  - name: 'Setup Node.js 14'
    uses: actions/setup-node@v2
    with:
      node-version: 14.x

  - name: 'Install npm packages'
    run: npm install

  - name: Setup Git
    run: |
      git config user.name 'Myles Borins'
      git config user.email 'myles.borins@gmail.com'

  - name: bump version
    run: npm version ${{ github.event.inputs.version }}

  - name: Push latest version
    run: git push origin main --follow-tags

