name: 'Publish to npm'
description: 'Publish a package to npm'

runs:
  using: 'composite'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Publish
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm ci
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    