name: 'Increment Version'

on: 
  workflow_call:
    inputs:
      version:
        description: 'The argument to pass to npm version'
        required: true
        default: 'patch'
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: 'Install npm packages'
        run: npm ci

      - name: Setup Git
        run: |
          git config user.name 'Myles Borins'
          git config user.email 'myles.borins@gmail.com'

      - name: bump version
        run: npm version ${{ inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags
