name: Bump version

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Semver type of new version (major / minor / patch)'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  npm-version:
    uses: mylesborins/xml-sanitizer/.github/workflows/_increment-version.yml@main
    with:
      version: ${{ github.event.inputs.version }}

  publish-to-npm:
    uses: mylesborins/xml-sanitizer/.github/workflows/_publish-to-npm.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs: npm-version

  create-github-release:
    uses: mylesborins/xml-sanitizer/.github/workflows/_create-github-release.yml@main
    needs: publish-to-npm
