on:
  push:
    tags:
      - 'v*'

name: 'Create Release From Tag'

jobs:
  publish-to-npm:
    uses: mylesborins/reusable-workflows/.github/workflows/publish-to-npm.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    uses: mylesborins/reusable-workflows/.github/workflows/create-github-release.yml@main
    needs: publish-to-npm
