on:
  push:
    tags:
      - 'v*'

name: 'Create Release From Tag'

jobs:
  publish-to-npm:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
    - name: Setup node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
        cache: npm
    - name: Install dependencies and build
      run: npm ci
    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    uses: mylesborins/reusable-workflows/.github/workflows/create-github-release.yml@main
    needs: publish-to-npm
